[".oh-my-zsh"]
    type = "archive"
    url = "https://github.com/ohmyzsh/ohmyzsh/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
[".oh-my-zsh/custom/plugins/zsh-syntax-highlighting"]
    type = "archive"
    url = "https://github.com/zsh-users/zsh-syntax-highlighting/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
[".oh-my-zsh/custom/themes/powerlevel10k"]
    type = "archive"
    url = "https://github.com/romkatv/powerlevel10k/archive/v1.15.0.tar.gz"
    exact = true
    stripComponents = 1
[".oh-my-zsh/custom/themes/af-magic-shlvl-awsprofile.zsh-theme"]
	type = "file"
	url = "https://gist.githubusercontent.com/clocklear/ba7ea8849d0a36141cd72e356d7e4a8a/raw/4c0fd70c537a32800509fa65d98906853c98be1f/af-magic-shlvl-awsprofile.zsh-theme"
    refreshPeriod = "672h"
[".oh-my-zsh/custom/themes/af-magic-shlvl.zsh-theme"]
	type = "file"
	url = "https://gist.githubusercontent.com/clocklear/ba7ea8849d0a36141cd72e356d7e4a8a/raw/4c0fd70c537a32800509fa65d98906853c98be1f/af-magic-shlvl.zsh-theme"
    refreshPeriod = "672h"    
["antigen.zsh"]
	type = "file"
	url = "https://git.io/antigen"
	refreshPeriod = "168h"
[".vim/autoload/pathogen.vim"]
	type = "file"
	url = "https://tpo.pe/pathogen.vim"
	refreshPeriod = "672h"
[".vim/bundle/base16-vim"]
	type = "archive"
	url = "https://github.com/chriskempson/base16-vim/archive/master.tar.gz"
	exact = true
	stripComponents = 1
	refreshPeriod = "672h"
[".vim/bundle/nerdtree"]
    type = "archive"
    url = "https://github.com/preservim/nerdtree/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "672h"
[".vim/bundle/ale"]
    type = "archive"
    url = "https://github.com/dense-analysis/ale/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "672h"
[".vim/bundle/copilot.vim"]
    type = "archive"
    url = "https://github.com/github/copilot.vim/archive/release.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "336h"
[".vim/bundle/vim-airline"]
    type = "archive"
    url = "https://github.com/vim-airline/vim-airline/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "672h"
